---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml

# Call handlers
- meta: flush_handlers

- name: check postgresql service state
  service:
    name: postgresql
    state: "{{ (postgresql_service_state == 'stopped') | ternary('stopped', 'started') }}"

# Configure PostgreSQL.
- import_tasks: users.yml
  when: postgresql_service_state != 'stopped'

- import_tasks: databases.yml
  when: postgresql_service_state != 'stopped'
